language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "1//0g_H3HzJnPqjgCgYIARAAGBASNwF-L9IruXIKdOWEWj-gdFStYvLL-VyzvsY4U4oow5Gk_ZCTAhgR2e7xw5H_vVqFfiLOPQDaskA"